/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.cartservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/cartservice/cart_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as api_common_proto_cartservice_cart_service_pb from '../../../../api/common/proto/cartservice/cart_service_pb'; // proto import: "api/common/proto/cartservice/cart_service.proto"


export class CartServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetCartItems = new grpcWeb.MethodDescriptor(
    '/api.common.proto.cartservice.CartService/GetCartItems',
    grpcWeb.MethodType.UNARY,
    api_common_proto_cartservice_cart_service_pb.GetCartItemsRequest,
    api_common_proto_cartservice_cart_service_pb.GetCartItemsResponse,
    (request: api_common_proto_cartservice_cart_service_pb.GetCartItemsRequest) => {
      return request.serializeBinary();
    },
    api_common_proto_cartservice_cart_service_pb.GetCartItemsResponse.deserializeBinary
  );

  getCartItems(
    request: api_common_proto_cartservice_cart_service_pb.GetCartItemsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_common_proto_cartservice_cart_service_pb.GetCartItemsResponse>;

  getCartItems(
    request: api_common_proto_cartservice_cart_service_pb.GetCartItemsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_common_proto_cartservice_cart_service_pb.GetCartItemsResponse) => void): grpcWeb.ClientReadableStream<api_common_proto_cartservice_cart_service_pb.GetCartItemsResponse>;

  getCartItems(
    request: api_common_proto_cartservice_cart_service_pb.GetCartItemsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_common_proto_cartservice_cart_service_pb.GetCartItemsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.common.proto.cartservice.CartService/GetCartItems',
        request,
        metadata || {},
        this.methodDescriptorGetCartItems,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.common.proto.cartservice.CartService/GetCartItems',
    request,
    metadata || {},
    this.methodDescriptorGetCartItems);
  }

  methodDescriptorMutateCart = new grpcWeb.MethodDescriptor(
    '/api.common.proto.cartservice.CartService/MutateCart',
    grpcWeb.MethodType.UNARY,
    api_common_proto_cartservice_cart_service_pb.MutateCartRequest,
    api_common_proto_cartservice_cart_service_pb.MutateCartResponse,
    (request: api_common_proto_cartservice_cart_service_pb.MutateCartRequest) => {
      return request.serializeBinary();
    },
    api_common_proto_cartservice_cart_service_pb.MutateCartResponse.deserializeBinary
  );

  mutateCart(
    request: api_common_proto_cartservice_cart_service_pb.MutateCartRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_common_proto_cartservice_cart_service_pb.MutateCartResponse>;

  mutateCart(
    request: api_common_proto_cartservice_cart_service_pb.MutateCartRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_common_proto_cartservice_cart_service_pb.MutateCartResponse) => void): grpcWeb.ClientReadableStream<api_common_proto_cartservice_cart_service_pb.MutateCartResponse>;

  mutateCart(
    request: api_common_proto_cartservice_cart_service_pb.MutateCartRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_common_proto_cartservice_cart_service_pb.MutateCartResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.common.proto.cartservice.CartService/MutateCart',
        request,
        metadata || {},
        this.methodDescriptorMutateCart,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.common.proto.cartservice.CartService/MutateCart',
    request,
    metadata || {},
    this.methodDescriptorMutateCart);
  }

}

