// source: api/common/proto/store.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.exportSymbol('proto.api.common.proto.Store', null, global);
goog.exportSymbol('proto.api.common.proto.Store.PrimaryKey', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.Store = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.common.proto.Store.repeatedFields_, null);
};
goog.inherits(proto.api.common.proto.Store, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.Store.displayName = 'proto.api.common.proto.Store';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.Store.PrimaryKey = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.Store.PrimaryKey, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.Store.PrimaryKey.displayName = 'proto.api.common.proto.Store.PrimaryKey';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.common.proto.Store.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.Store.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.Store.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.Store} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.Store.toObject = function(includeInstance, msg) {
  var f, obj = {
primaryKey: (f = msg.getPrimaryKey()) && proto.api.common.proto.Store.PrimaryKey.toObject(includeInstance, f),
websiteUrl: jspb.Message.getFieldWithDefault(msg, 2, ""),
imageUrlsList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
name: jspb.Message.getFieldWithDefault(msg, 4, ""),
description: jspb.Message.getFieldWithDefault(msg, 5, ""),
address: (f = msg.getAddress()) && proto.api.common.proto.Address.toObject(includeInstance, f),
distanceInMeters: jspb.Message.getFieldWithDefault(msg, 8, 0),
timeInMillis: jspb.Message.getFieldWithDefault(msg, 9, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.Store}
 */
proto.api.common.proto.Store.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.Store;
  return proto.api.common.proto.Store.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.Store} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.Store}
 */
proto.api.common.proto.Store.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.Store.PrimaryKey;
      reader.readMessage(value,proto.api.common.proto.Store.PrimaryKey.deserializeBinaryFromReader);
      msg.setPrimaryKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWebsiteUrl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addImageUrls(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = new proto.api.common.proto.Address;
      reader.readMessage(value,proto.api.common.proto.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDistanceInMeters(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeInMillis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.Store.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.Store.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.Store} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.Store.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPrimaryKey();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.Store.PrimaryKey.serializeBinaryToWriter
    );
  }
  f = message.getWebsiteUrl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getImageUrlsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.api.common.proto.Address.serializeBinaryToWriter
    );
  }
  f = message.getDistanceInMeters();
  if (f !== 0) {
    writer.writeInt64(
      8,
      f
    );
  }
  f = message.getTimeInMillis();
  if (f !== 0) {
    writer.writeInt64(
      9,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.Store.PrimaryKey.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.Store.PrimaryKey.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.Store.PrimaryKey} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.Store.PrimaryKey.toObject = function(includeInstance, msg) {
  var f, obj = {
storeId: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.Store.PrimaryKey}
 */
proto.api.common.proto.Store.PrimaryKey.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.Store.PrimaryKey;
  return proto.api.common.proto.Store.PrimaryKey.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.Store.PrimaryKey} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.Store.PrimaryKey}
 */
proto.api.common.proto.Store.PrimaryKey.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStoreId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.Store.PrimaryKey.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.Store.PrimaryKey.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.Store.PrimaryKey} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.Store.PrimaryKey.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStoreId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
};


/**
 * optional int64 store_id = 1;
 * @return {number}
 */
proto.api.common.proto.Store.PrimaryKey.prototype.getStoreId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.Store.PrimaryKey} returns this
 */
proto.api.common.proto.Store.PrimaryKey.prototype.setStoreId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional PrimaryKey primary_key = 1;
 * @return {?proto.api.common.proto.Store.PrimaryKey}
 */
proto.api.common.proto.Store.prototype.getPrimaryKey = function() {
  return /** @type{?proto.api.common.proto.Store.PrimaryKey} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.Store.PrimaryKey, 1));
};


/**
 * @param {?proto.api.common.proto.Store.PrimaryKey|undefined} value
 * @return {!proto.api.common.proto.Store} returns this
*/
proto.api.common.proto.Store.prototype.setPrimaryKey = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.clearPrimaryKey = function() {
  return this.setPrimaryKey(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.Store.prototype.hasPrimaryKey = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string website_url = 2;
 * @return {string}
 */
proto.api.common.proto.Store.prototype.getWebsiteUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.setWebsiteUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string image_urls = 3;
 * @return {!Array<string>}
 */
proto.api.common.proto.Store.prototype.getImageUrlsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.setImageUrlsList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.addImageUrls = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.clearImageUrlsList = function() {
  return this.setImageUrlsList([]);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.api.common.proto.Store.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string description = 5;
 * @return {string}
 */
proto.api.common.proto.Store.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Address address = 7;
 * @return {?proto.api.common.proto.Address}
 */
proto.api.common.proto.Store.prototype.getAddress = function() {
  return /** @type{?proto.api.common.proto.Address} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.Address, 7));
};


/**
 * @param {?proto.api.common.proto.Address|undefined} value
 * @return {!proto.api.common.proto.Store} returns this
*/
proto.api.common.proto.Store.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.Store.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional int64 distance_in_meters = 8;
 * @return {number}
 */
proto.api.common.proto.Store.prototype.getDistanceInMeters = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.setDistanceInMeters = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int64 time_in_millis = 9;
 * @return {number}
 */
proto.api.common.proto.Store.prototype.getTimeInMillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.Store} returns this
 */
proto.api.common.proto.Store.prototype.setTimeInMillis = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


