// @generated by protobuf-ts 2.11.0
// @generated from protobuf file "api/common/enums/order_status.proto" (package "api.common.enums", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message api.common.enums.OrderStatus
 */
export interface OrderStatus {
}
/**
 * @generated from protobuf enum api.common.enums.OrderStatus.Enum
 */
export enum OrderStatus_Enum {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: ORDER_PLACED = 1;
     */
    ORDER_PLACED = 1,
    /**
     * @generated from protobuf enum value: DELIVERY_PARTNER_ASSIGNED = 2;
     */
    DELIVERY_PARTNER_ASSIGNED = 2,
    /**
     * @generated from protobuf enum value: PICKED = 3;
     */
    PICKED = 3,
    /**
     * @generated from protobuf enum value: DELIVERED = 4;
     */
    DELIVERED = 4,
    /**
     * @generated from protobuf enum value: WAITING = 5;
     */
    WAITING = 5,
    /**
     * @generated from protobuf enum value: REFUND_PENDING = 6;
     */
    REFUND_PENDING = 6,
    /**
     * @generated from protobuf enum value: COMPLETED = 7;
     */
    COMPLETED = 7
}
// @generated message type with reflection information, may provide speed optimized methods
class OrderStatus$Type extends MessageType<OrderStatus> {
    constructor() {
        super("api.common.enums.OrderStatus", []);
    }
    create(value?: PartialMessage<OrderStatus>): OrderStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<OrderStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrderStatus): OrderStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrderStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message api.common.enums.OrderStatus
 */
export const OrderStatus = new OrderStatus$Type();
