// source: api/common/proto/productservice/product_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.exportSymbol('proto.api.common.proto.productservice.Field', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.Field.Enum', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetCategorySetRequest', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetCategorySetResponse', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetProductDetailsRequest', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetProductDetailsResponse', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetProductRequest', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetProductRequest.OrderBy', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.GetProductResponse', null, global);
goog.exportSymbol('proto.api.common.proto.productservice.ProductSelector', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetCategorySetRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.GetCategorySetRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetCategorySetRequest.displayName = 'proto.api.common.proto.productservice.GetCategorySetRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetCategorySetResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.GetCategorySetResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetCategorySetResponse.displayName = 'proto.api.common.proto.productservice.GetCategorySetResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetProductDetailsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.GetProductDetailsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetProductDetailsRequest.displayName = 'proto.api.common.proto.productservice.GetProductDetailsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetProductDetailsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.GetProductDetailsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetProductDetailsResponse.displayName = 'proto.api.common.proto.productservice.GetProductDetailsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetProductRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.common.proto.productservice.GetProductRequest.repeatedFields_, null);
};
goog.inherits(proto.api.common.proto.productservice.GetProductRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetProductRequest.displayName = 'proto.api.common.proto.productservice.GetProductRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.GetProductRequest.OrderBy, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetProductRequest.OrderBy.displayName = 'proto.api.common.proto.productservice.GetProductRequest.OrderBy';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.GetProductResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.common.proto.productservice.GetProductResponse.repeatedFields_, null);
};
goog.inherits(proto.api.common.proto.productservice.GetProductResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.GetProductResponse.displayName = 'proto.api.common.proto.productservice.GetProductResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.ProductSelector = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.ProductSelector, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.ProductSelector.displayName = 'proto.api.common.proto.productservice.ProductSelector';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.productservice.Field = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.productservice.Field, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.productservice.Field.displayName = 'proto.api.common.proto.productservice.Field';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetCategorySetRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetCategorySetRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetCategorySetRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetCategorySetRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.RequestHeader.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetCategorySetRequest}
 */
proto.api.common.proto.productservice.GetCategorySetRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetCategorySetRequest;
  return proto.api.common.proto.productservice.GetCategorySetRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetCategorySetRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetCategorySetRequest}
 */
proto.api.common.proto.productservice.GetCategorySetRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.RequestHeader;
      reader.readMessage(value,proto.api.common.proto.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetCategorySetRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetCategorySetRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetCategorySetRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetCategorySetRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.RequestHeader.serializeBinaryToWriter
    );
  }
};


/**
 * optional api.common.proto.RequestHeader header = 1;
 * @return {?proto.api.common.proto.RequestHeader}
 */
proto.api.common.proto.productservice.GetCategorySetRequest.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.RequestHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.RequestHeader, 1));
};


/**
 * @param {?proto.api.common.proto.RequestHeader|undefined} value
 * @return {!proto.api.common.proto.productservice.GetCategorySetRequest} returns this
*/
proto.api.common.proto.productservice.GetCategorySetRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetCategorySetRequest} returns this
 */
proto.api.common.proto.productservice.GetCategorySetRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetCategorySetRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetCategorySetResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetCategorySetResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetCategorySetResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.ResponseHeader.toObject(includeInstance, f),
categorySet: (f = msg.getCategorySet()) && proto.api.common.proto.CategorySet.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetCategorySetResponse}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetCategorySetResponse;
  return proto.api.common.proto.productservice.GetCategorySetResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetCategorySetResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetCategorySetResponse}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.ResponseHeader;
      reader.readMessage(value,proto.api.common.proto.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.api.common.proto.CategorySet;
      reader.readMessage(value,proto.api.common.proto.CategorySet.deserializeBinaryFromReader);
      msg.setCategorySet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetCategorySetResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetCategorySetResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetCategorySetResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getCategorySet();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api.common.proto.CategorySet.serializeBinaryToWriter
    );
  }
};


/**
 * optional api.common.proto.ResponseHeader header = 1;
 * @return {?proto.api.common.proto.ResponseHeader}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ResponseHeader, 1));
};


/**
 * @param {?proto.api.common.proto.ResponseHeader|undefined} value
 * @return {!proto.api.common.proto.productservice.GetCategorySetResponse} returns this
*/
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetCategorySetResponse} returns this
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional api.common.proto.CategorySet category_set = 2;
 * @return {?proto.api.common.proto.CategorySet}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.getCategorySet = function() {
  return /** @type{?proto.api.common.proto.CategorySet} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.CategorySet, 2));
};


/**
 * @param {?proto.api.common.proto.CategorySet|undefined} value
 * @return {!proto.api.common.proto.productservice.GetCategorySetResponse} returns this
*/
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.setCategorySet = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetCategorySetResponse} returns this
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.clearCategorySet = function() {
  return this.setCategorySet(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetCategorySetResponse.prototype.hasCategorySet = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetProductDetailsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetProductDetailsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.RequestHeader.toObject(includeInstance, f),
productId: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsRequest}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetProductDetailsRequest;
  return proto.api.common.proto.productservice.GetProductDetailsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetProductDetailsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsRequest}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.RequestHeader;
      reader.readMessage(value,proto.api.common.proto.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProductId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetProductDetailsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetProductDetailsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.RequestHeader.serializeBinaryToWriter
    );
  }
  f = message.getProductId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * optional api.common.proto.RequestHeader header = 1;
 * @return {?proto.api.common.proto.RequestHeader}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.RequestHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.RequestHeader, 1));
};


/**
 * @param {?proto.api.common.proto.RequestHeader|undefined} value
 * @return {!proto.api.common.proto.productservice.GetProductDetailsRequest} returns this
*/
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsRequest} returns this
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int64 product_id = 2;
 * @return {number}
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.getProductId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.productservice.GetProductDetailsRequest} returns this
 */
proto.api.common.proto.productservice.GetProductDetailsRequest.prototype.setProductId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetProductDetailsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetProductDetailsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.ResponseHeader.toObject(includeInstance, f),
productDetails: (f = msg.getProductDetails()) && proto.api.common.proto.ProductDetails.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsResponse}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetProductDetailsResponse;
  return proto.api.common.proto.productservice.GetProductDetailsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetProductDetailsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsResponse}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.ResponseHeader;
      reader.readMessage(value,proto.api.common.proto.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.api.common.proto.ProductDetails;
      reader.readMessage(value,proto.api.common.proto.ProductDetails.deserializeBinaryFromReader);
      msg.setProductDetails(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetProductDetailsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetProductDetailsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getProductDetails();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api.common.proto.ProductDetails.serializeBinaryToWriter
    );
  }
};


/**
 * optional api.common.proto.ResponseHeader header = 1;
 * @return {?proto.api.common.proto.ResponseHeader}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ResponseHeader, 1));
};


/**
 * @param {?proto.api.common.proto.ResponseHeader|undefined} value
 * @return {!proto.api.common.proto.productservice.GetProductDetailsResponse} returns this
*/
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsResponse} returns this
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional api.common.proto.ProductDetails product_details = 2;
 * @return {?proto.api.common.proto.ProductDetails}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.getProductDetails = function() {
  return /** @type{?proto.api.common.proto.ProductDetails} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ProductDetails, 2));
};


/**
 * @param {?proto.api.common.proto.ProductDetails|undefined} value
 * @return {!proto.api.common.proto.productservice.GetProductDetailsResponse} returns this
*/
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.setProductDetails = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetProductDetailsResponse} returns this
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.clearProductDetails = function() {
  return this.setProductDetails(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetProductDetailsResponse.prototype.hasProductDetails = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.common.proto.productservice.GetProductRequest.repeatedFields_ = [3,4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetProductRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetProductRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.RequestHeader.toObject(includeInstance, f),
searchQuery: jspb.Message.getFieldWithDefault(msg, 2, ""),
selectorsList: jspb.Message.toObjectList(msg.getSelectorsList(),
    proto.api.common.proto.productservice.ProductSelector.toObject, includeInstance),
orderByList: jspb.Message.toObjectList(msg.getOrderByList(),
    proto.api.common.proto.productservice.GetProductRequest.OrderBy.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetProductRequest}
 */
proto.api.common.proto.productservice.GetProductRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetProductRequest;
  return proto.api.common.proto.productservice.GetProductRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetProductRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetProductRequest}
 */
proto.api.common.proto.productservice.GetProductRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.RequestHeader;
      reader.readMessage(value,proto.api.common.proto.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSearchQuery(value);
      break;
    case 3:
      var value = new proto.api.common.proto.productservice.ProductSelector;
      reader.readMessage(value,proto.api.common.proto.productservice.ProductSelector.deserializeBinaryFromReader);
      msg.addSelectors(value);
      break;
    case 4:
      var value = new proto.api.common.proto.productservice.GetProductRequest.OrderBy;
      reader.readMessage(value,proto.api.common.proto.productservice.GetProductRequest.OrderBy.deserializeBinaryFromReader);
      msg.addOrderBy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetProductRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetProductRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.RequestHeader.serializeBinaryToWriter
    );
  }
  f = message.getSearchQuery();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSelectorsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.api.common.proto.productservice.ProductSelector.serializeBinaryToWriter
    );
  }
  f = message.getOrderByList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.api.common.proto.productservice.GetProductRequest.OrderBy.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetProductRequest.OrderBy.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetProductRequest.OrderBy} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.toObject = function(includeInstance, msg) {
  var f, obj = {
selector: jspb.Message.getFieldWithDefault(msg, 1, 0),
descending: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetProductRequest.OrderBy}
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetProductRequest.OrderBy;
  return proto.api.common.proto.productservice.GetProductRequest.OrderBy.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetProductRequest.OrderBy} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetProductRequest.OrderBy}
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.api.common.proto.productservice.Field.Enum} */ (reader.readEnum());
      msg.setSelector(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setDescending(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetProductRequest.OrderBy.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetProductRequest.OrderBy} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSelector();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getDescending();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional Field.Enum selector = 1;
 * @return {!proto.api.common.proto.productservice.Field.Enum}
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.prototype.getSelector = function() {
  return /** @type {!proto.api.common.proto.productservice.Field.Enum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.api.common.proto.productservice.Field.Enum} value
 * @return {!proto.api.common.proto.productservice.GetProductRequest.OrderBy} returns this
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.prototype.setSelector = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool descending = 2;
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.prototype.getDescending = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api.common.proto.productservice.GetProductRequest.OrderBy} returns this
 */
proto.api.common.proto.productservice.GetProductRequest.OrderBy.prototype.setDescending = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional api.common.proto.RequestHeader header = 1;
 * @return {?proto.api.common.proto.RequestHeader}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.RequestHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.RequestHeader, 1));
};


/**
 * @param {?proto.api.common.proto.RequestHeader|undefined} value
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
*/
proto.api.common.proto.productservice.GetProductRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string search_query = 2;
 * @return {string}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.getSearchQuery = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.setSearchQuery = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated ProductSelector selectors = 3;
 * @return {!Array<!proto.api.common.proto.productservice.ProductSelector>}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.getSelectorsList = function() {
  return /** @type{!Array<!proto.api.common.proto.productservice.ProductSelector>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.common.proto.productservice.ProductSelector, 3));
};


/**
 * @param {!Array<!proto.api.common.proto.productservice.ProductSelector>} value
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
*/
proto.api.common.proto.productservice.GetProductRequest.prototype.setSelectorsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.api.common.proto.productservice.ProductSelector=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.common.proto.productservice.ProductSelector}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.addSelectors = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.api.common.proto.productservice.ProductSelector, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.clearSelectorsList = function() {
  return this.setSelectorsList([]);
};


/**
 * repeated OrderBy order_by = 4;
 * @return {!Array<!proto.api.common.proto.productservice.GetProductRequest.OrderBy>}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.getOrderByList = function() {
  return /** @type{!Array<!proto.api.common.proto.productservice.GetProductRequest.OrderBy>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.common.proto.productservice.GetProductRequest.OrderBy, 4));
};


/**
 * @param {!Array<!proto.api.common.proto.productservice.GetProductRequest.OrderBy>} value
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
*/
proto.api.common.proto.productservice.GetProductRequest.prototype.setOrderByList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.api.common.proto.productservice.GetProductRequest.OrderBy=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.common.proto.productservice.GetProductRequest.OrderBy}
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.addOrderBy = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.api.common.proto.productservice.GetProductRequest.OrderBy, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.common.proto.productservice.GetProductRequest} returns this
 */
proto.api.common.proto.productservice.GetProductRequest.prototype.clearOrderByList = function() {
  return this.setOrderByList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.common.proto.productservice.GetProductResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.GetProductResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.GetProductResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.ResponseHeader.toObject(includeInstance, f),
productsList: jspb.Message.toObjectList(msg.getProductsList(),
    proto.api.common.proto.Product.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.GetProductResponse}
 */
proto.api.common.proto.productservice.GetProductResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.GetProductResponse;
  return proto.api.common.proto.productservice.GetProductResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.GetProductResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.GetProductResponse}
 */
proto.api.common.proto.productservice.GetProductResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.ResponseHeader;
      reader.readMessage(value,proto.api.common.proto.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.api.common.proto.Product;
      reader.readMessage(value,proto.api.common.proto.Product.deserializeBinaryFromReader);
      msg.addProducts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.GetProductResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.GetProductResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.GetProductResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getProductsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.api.common.proto.Product.serializeBinaryToWriter
    );
  }
};


/**
 * optional api.common.proto.ResponseHeader header = 1;
 * @return {?proto.api.common.proto.ResponseHeader}
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ResponseHeader, 1));
};


/**
 * @param {?proto.api.common.proto.ResponseHeader|undefined} value
 * @return {!proto.api.common.proto.productservice.GetProductResponse} returns this
*/
proto.api.common.proto.productservice.GetProductResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.GetProductResponse} returns this
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated api.common.proto.Product products = 2;
 * @return {!Array<!proto.api.common.proto.Product>}
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.getProductsList = function() {
  return /** @type{!Array<!proto.api.common.proto.Product>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.common.proto.Product, 2));
};


/**
 * @param {!Array<!proto.api.common.proto.Product>} value
 * @return {!proto.api.common.proto.productservice.GetProductResponse} returns this
*/
proto.api.common.proto.productservice.GetProductResponse.prototype.setProductsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.api.common.proto.Product=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.common.proto.Product}
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.addProducts = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.api.common.proto.Product, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.common.proto.productservice.GetProductResponse} returns this
 */
proto.api.common.proto.productservice.GetProductResponse.prototype.clearProductsList = function() {
  return this.setProductsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.ProductSelector.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.ProductSelector.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.ProductSelector} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.ProductSelector.toObject = function(includeInstance, msg) {
  var f, obj = {
field: jspb.Message.getFieldWithDefault(msg, 1, 0),
filter: (f = msg.getFilter()) && proto.api.common.proto.Filter.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.ProductSelector}
 */
proto.api.common.proto.productservice.ProductSelector.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.ProductSelector;
  return proto.api.common.proto.productservice.ProductSelector.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.ProductSelector} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.ProductSelector}
 */
proto.api.common.proto.productservice.ProductSelector.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.api.common.proto.productservice.Field.Enum} */ (reader.readEnum());
      msg.setField(value);
      break;
    case 2:
      var value = new proto.api.common.proto.Filter;
      reader.readMessage(value,proto.api.common.proto.Filter.deserializeBinaryFromReader);
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.ProductSelector.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.ProductSelector.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.ProductSelector} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.ProductSelector.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getFilter();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.api.common.proto.Filter.serializeBinaryToWriter
    );
  }
};


/**
 * optional Field.Enum field = 1;
 * @return {!proto.api.common.proto.productservice.Field.Enum}
 */
proto.api.common.proto.productservice.ProductSelector.prototype.getField = function() {
  return /** @type {!proto.api.common.proto.productservice.Field.Enum} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.api.common.proto.productservice.Field.Enum} value
 * @return {!proto.api.common.proto.productservice.ProductSelector} returns this
 */
proto.api.common.proto.productservice.ProductSelector.prototype.setField = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional api.common.proto.Filter filter = 2;
 * @return {?proto.api.common.proto.Filter}
 */
proto.api.common.proto.productservice.ProductSelector.prototype.getFilter = function() {
  return /** @type{?proto.api.common.proto.Filter} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.Filter, 2));
};


/**
 * @param {?proto.api.common.proto.Filter|undefined} value
 * @return {!proto.api.common.proto.productservice.ProductSelector} returns this
*/
proto.api.common.proto.productservice.ProductSelector.prototype.setFilter = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.productservice.ProductSelector} returns this
 */
proto.api.common.proto.productservice.ProductSelector.prototype.clearFilter = function() {
  return this.setFilter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.productservice.ProductSelector.prototype.hasFilter = function() {
  return jspb.Message.getField(this, 2) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.productservice.Field.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.productservice.Field.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.productservice.Field} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.Field.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.productservice.Field}
 */
proto.api.common.proto.productservice.Field.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.productservice.Field;
  return proto.api.common.proto.productservice.Field.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.productservice.Field} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.productservice.Field}
 */
proto.api.common.proto.productservice.Field.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.productservice.Field.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.productservice.Field.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.productservice.Field} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.productservice.Field.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


/**
 * @enum {number}
 */
proto.api.common.proto.productservice.Field.Enum = {
  UNKNOWN: 0,
  PRODUCT_KEY: 1,
  BRAND_KEY: 2,
  STORE_KEY: 3,
  PRODUCT_VARIANT_KEY: 4,
  GENDER: 5,
  CATEGORY: 6,
  RATING: 7,
  DISCOUNT_PRICE_MICROS: 8,
  DISCOUNT_PERCENTAGE: 9,
  DISTANCE: 10,
  OFFER: 11,
  FROM_DELIVERY_PARTNERS: 12,
  CATEGORY_ID: 13
};

