// source: api/common/proto/orderservice/order_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.exportSymbol('proto.api.common.proto.orderservice.ConfirmPaymentRequest', null, global);
goog.exportSymbol('proto.api.common.proto.orderservice.ConfirmPaymentResponse', null, global);
goog.exportSymbol('proto.api.common.proto.orderservice.PlaceOrderRequest', null, global);
goog.exportSymbol('proto.api.common.proto.orderservice.PlaceOrderResponse', null, global);
goog.exportSymbol('proto.api.common.proto.orderservice.ProductVariantWithQuantity', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.orderservice.PlaceOrderRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.common.proto.orderservice.PlaceOrderRequest.repeatedFields_, null);
};
goog.inherits(proto.api.common.proto.orderservice.PlaceOrderRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.orderservice.PlaceOrderRequest.displayName = 'proto.api.common.proto.orderservice.PlaceOrderRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.orderservice.PlaceOrderResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.orderservice.PlaceOrderResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.orderservice.PlaceOrderResponse.displayName = 'proto.api.common.proto.orderservice.PlaceOrderResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.orderservice.ProductVariantWithQuantity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.orderservice.ProductVariantWithQuantity.displayName = 'proto.api.common.proto.orderservice.ProductVariantWithQuantity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.orderservice.ConfirmPaymentRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.orderservice.ConfirmPaymentRequest.displayName = 'proto.api.common.proto.orderservice.ConfirmPaymentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.orderservice.ConfirmPaymentResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.orderservice.ConfirmPaymentResponse.displayName = 'proto.api.common.proto.orderservice.ConfirmPaymentResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.orderservice.PlaceOrderRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.orderservice.PlaceOrderRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
productVariantsWithQuantityList: jspb.Message.toObjectList(msg.getProductVariantsWithQuantityList(),
    proto.api.common.proto.orderservice.ProductVariantWithQuantity.toObject, includeInstance),
customerAddressLinkId: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.orderservice.PlaceOrderRequest}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.orderservice.PlaceOrderRequest;
  return proto.api.common.proto.orderservice.PlaceOrderRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.orderservice.PlaceOrderRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.orderservice.PlaceOrderRequest}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.orderservice.ProductVariantWithQuantity;
      reader.readMessage(value,proto.api.common.proto.orderservice.ProductVariantWithQuantity.deserializeBinaryFromReader);
      msg.addProductVariantsWithQuantity(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCustomerAddressLinkId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.orderservice.PlaceOrderRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.orderservice.PlaceOrderRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductVariantsWithQuantityList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.api.common.proto.orderservice.ProductVariantWithQuantity.serializeBinaryToWriter
    );
  }
  f = message.getCustomerAddressLinkId();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
};


/**
 * repeated ProductVariantWithQuantity product_variants_with_quantity = 1;
 * @return {!Array<!proto.api.common.proto.orderservice.ProductVariantWithQuantity>}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.getProductVariantsWithQuantityList = function() {
  return /** @type{!Array<!proto.api.common.proto.orderservice.ProductVariantWithQuantity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.common.proto.orderservice.ProductVariantWithQuantity, 1));
};


/**
 * @param {!Array<!proto.api.common.proto.orderservice.ProductVariantWithQuantity>} value
 * @return {!proto.api.common.proto.orderservice.PlaceOrderRequest} returns this
*/
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.setProductVariantsWithQuantityList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.api.common.proto.orderservice.ProductVariantWithQuantity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.common.proto.orderservice.ProductVariantWithQuantity}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.addProductVariantsWithQuantity = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.api.common.proto.orderservice.ProductVariantWithQuantity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.common.proto.orderservice.PlaceOrderRequest} returns this
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.clearProductVariantsWithQuantityList = function() {
  return this.setProductVariantsWithQuantityList([]);
};


/**
 * optional int64 customer_address_link_id = 2;
 * @return {number}
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.getCustomerAddressLinkId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.orderservice.PlaceOrderRequest} returns this
 */
proto.api.common.proto.orderservice.PlaceOrderRequest.prototype.setCustomerAddressLinkId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.orderservice.PlaceOrderResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.orderservice.PlaceOrderResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.ResponseHeader.toObject(includeInstance, f),
orderNumber: jspb.Message.getFieldWithDefault(msg, 2, ""),
razorpayOrderId: jspb.Message.getFieldWithDefault(msg, 3, ""),
amountMicros: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.orderservice.PlaceOrderResponse;
  return proto.api.common.proto.orderservice.PlaceOrderResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.orderservice.PlaceOrderResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.ResponseHeader;
      reader.readMessage(value,proto.api.common.proto.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRazorpayOrderId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setAmountMicros(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.orderservice.PlaceOrderResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.orderservice.PlaceOrderResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getOrderNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRazorpayOrderId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAmountMicros();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional api.common.proto.ResponseHeader header = 1;
 * @return {?proto.api.common.proto.ResponseHeader}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ResponseHeader, 1));
};


/**
 * @param {?proto.api.common.proto.ResponseHeader|undefined} value
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse} returns this
*/
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse} returns this
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string order_number = 2;
 * @return {string}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.getOrderNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse} returns this
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.setOrderNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string razorpay_order_id = 3;
 * @return {string}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.getRazorpayOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse} returns this
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.setRazorpayOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 amount_micros = 4;
 * @return {number}
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.getAmountMicros = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.orderservice.PlaceOrderResponse} returns this
 */
proto.api.common.proto.orderservice.PlaceOrderResponse.prototype.setAmountMicros = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.orderservice.ProductVariantWithQuantity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.orderservice.ProductVariantWithQuantity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.toObject = function(includeInstance, msg) {
  var f, obj = {
productVariantId: jspb.Message.getFieldWithDefault(msg, 1, 0),
quantity: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.orderservice.ProductVariantWithQuantity}
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.orderservice.ProductVariantWithQuantity;
  return proto.api.common.proto.orderservice.ProductVariantWithQuantity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.orderservice.ProductVariantWithQuantity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.orderservice.ProductVariantWithQuantity}
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProductVariantId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.orderservice.ProductVariantWithQuantity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.orderservice.ProductVariantWithQuantity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductVariantId();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
};


/**
 * optional int64 product_variant_id = 1;
 * @return {number}
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.prototype.getProductVariantId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.orderservice.ProductVariantWithQuantity} returns this
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.prototype.setProductVariantId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 quantity = 2;
 * @return {number}
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.api.common.proto.orderservice.ProductVariantWithQuantity} returns this
 */
proto.api.common.proto.orderservice.ProductVariantWithQuantity.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.orderservice.ConfirmPaymentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
razorpayOrderId: jspb.Message.getFieldWithDefault(msg, 1, ""),
razorpayPaymentId: jspb.Message.getFieldWithDefault(msg, 2, ""),
razorpaySignature: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentRequest}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.orderservice.ConfirmPaymentRequest;
  return proto.api.common.proto.orderservice.ConfirmPaymentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentRequest}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRazorpayOrderId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRazorpayPaymentId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRazorpaySignature(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.orderservice.ConfirmPaymentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRazorpayOrderId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRazorpayPaymentId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRazorpaySignature();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string razorpay_order_id = 1;
 * @return {string}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.getRazorpayOrderId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} returns this
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.setRazorpayOrderId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string razorpay_payment_id = 2;
 * @return {string}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.getRazorpayPaymentId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} returns this
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.setRazorpayPaymentId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string razorpay_signature = 3;
 * @return {string}
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.getRazorpaySignature = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentRequest} returns this
 */
proto.api.common.proto.orderservice.ConfirmPaymentRequest.prototype.setRazorpaySignature = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.orderservice.ConfirmPaymentResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.ResponseHeader.toObject(includeInstance, f),
success: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
orderNumber: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentResponse}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.orderservice.ConfirmPaymentResponse;
  return proto.api.common.proto.orderservice.ConfirmPaymentResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentResponse}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.ResponseHeader;
      reader.readMessage(value,proto.api.common.proto.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrderNumber(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.orderservice.ConfirmPaymentResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getOrderNumber();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional api.common.proto.ResponseHeader header = 1;
 * @return {?proto.api.common.proto.ResponseHeader}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ResponseHeader, 1));
};


/**
 * @param {?proto.api.common.proto.ResponseHeader|undefined} value
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} returns this
*/
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} returns this
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool success = 2;
 * @return {boolean}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} returns this
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional string order_number = 3;
 * @return {string}
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.getOrderNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.api.common.proto.orderservice.ConfirmPaymentResponse} returns this
 */
proto.api.common.proto.orderservice.ConfirmPaymentResponse.prototype.setOrderNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


