/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.orderservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/orderservice/order_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as api_common_proto_orderservice_order_service_pb from '../../../../api/common/proto/orderservice/order_service_pb'; // proto import: "api/common/proto/orderservice/order_service.proto"


export class OrderServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPlaceOrder = new grpcWeb.MethodDescriptor(
    '/api.common.proto.orderservice.OrderService/PlaceOrder',
    grpcWeb.MethodType.UNARY,
    api_common_proto_orderservice_order_service_pb.PlaceOrderRequest,
    api_common_proto_orderservice_order_service_pb.PlaceOrderResponse,
    (request: api_common_proto_orderservice_order_service_pb.PlaceOrderRequest) => {
      return request.serializeBinary();
    },
    api_common_proto_orderservice_order_service_pb.PlaceOrderResponse.deserializeBinary
  );

  placeOrder(
    request: api_common_proto_orderservice_order_service_pb.PlaceOrderRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_common_proto_orderservice_order_service_pb.PlaceOrderResponse>;

  placeOrder(
    request: api_common_proto_orderservice_order_service_pb.PlaceOrderRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_common_proto_orderservice_order_service_pb.PlaceOrderResponse) => void): grpcWeb.ClientReadableStream<api_common_proto_orderservice_order_service_pb.PlaceOrderResponse>;

  placeOrder(
    request: api_common_proto_orderservice_order_service_pb.PlaceOrderRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_common_proto_orderservice_order_service_pb.PlaceOrderResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.common.proto.orderservice.OrderService/PlaceOrder',
        request,
        metadata || {},
        this.methodDescriptorPlaceOrder,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.common.proto.orderservice.OrderService/PlaceOrder',
    request,
    metadata || {},
    this.methodDescriptorPlaceOrder);
  }

  methodDescriptorConfirmPayment = new grpcWeb.MethodDescriptor(
    '/api.common.proto.orderservice.OrderService/ConfirmPayment',
    grpcWeb.MethodType.UNARY,
    api_common_proto_orderservice_order_service_pb.ConfirmPaymentRequest,
    api_common_proto_orderservice_order_service_pb.ConfirmPaymentResponse,
    (request: api_common_proto_orderservice_order_service_pb.ConfirmPaymentRequest) => {
      return request.serializeBinary();
    },
    api_common_proto_orderservice_order_service_pb.ConfirmPaymentResponse.deserializeBinary
  );

  confirmPayment(
    request: api_common_proto_orderservice_order_service_pb.ConfirmPaymentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_common_proto_orderservice_order_service_pb.ConfirmPaymentResponse>;

  confirmPayment(
    request: api_common_proto_orderservice_order_service_pb.ConfirmPaymentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_common_proto_orderservice_order_service_pb.ConfirmPaymentResponse) => void): grpcWeb.ClientReadableStream<api_common_proto_orderservice_order_service_pb.ConfirmPaymentResponse>;

  confirmPayment(
    request: api_common_proto_orderservice_order_service_pb.ConfirmPaymentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_common_proto_orderservice_order_service_pb.ConfirmPaymentResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.common.proto.orderservice.OrderService/ConfirmPayment',
        request,
        metadata || {},
        this.methodDescriptorConfirmPayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.common.proto.orderservice.OrderService/ConfirmPayment',
    request,
    metadata || {},
    this.methodDescriptorConfirmPayment);
  }

}

