/**
 * @fileoverview gRPC-Web generated client stub for api.common.proto.storeservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.2
// source: api/common/proto/storeservice/store_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as api_common_proto_storeservice_store_service_pb from '../../../../api/common/proto/storeservice/store_service_pb'; // proto import: "api/common/proto/storeservice/store_service.proto"


export class StoreServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetStore = new grpcWeb.MethodDescriptor(
    '/api.common.proto.storeservice.StoreService/GetStore',
    grpcWeb.MethodType.SERVER_STREAMING,
    api_common_proto_storeservice_store_service_pb.GetStoreRequest,
    api_common_proto_storeservice_store_service_pb.GetStoreResponse,
    (request: api_common_proto_storeservice_store_service_pb.GetStoreRequest) => {
      return request.serializeBinary();
    },
    api_common_proto_storeservice_store_service_pb.GetStoreResponse.deserializeBinary
  );

  getStore(
    request: api_common_proto_storeservice_store_service_pb.GetStoreRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<api_common_proto_storeservice_store_service_pb.GetStoreResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/api.common.proto.storeservice.StoreService/GetStore',
      request,
      metadata || {},
      this.methodDescriptorGetStore);
  }

  methodDescriptorGetStorePriceForProduct = new grpcWeb.MethodDescriptor(
    '/api.common.proto.storeservice.StoreService/GetStorePriceForProduct',
    grpcWeb.MethodType.UNARY,
    api_common_proto_storeservice_store_service_pb.GetStorePriceForProductRequest,
    api_common_proto_storeservice_store_service_pb.GetStorePriceForProductResponse,
    (request: api_common_proto_storeservice_store_service_pb.GetStorePriceForProductRequest) => {
      return request.serializeBinary();
    },
    api_common_proto_storeservice_store_service_pb.GetStorePriceForProductResponse.deserializeBinary
  );

  getStorePriceForProduct(
    request: api_common_proto_storeservice_store_service_pb.GetStorePriceForProductRequest,
    metadata?: grpcWeb.Metadata | null): Promise<api_common_proto_storeservice_store_service_pb.GetStorePriceForProductResponse>;

  getStorePriceForProduct(
    request: api_common_proto_storeservice_store_service_pb.GetStorePriceForProductRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: api_common_proto_storeservice_store_service_pb.GetStorePriceForProductResponse) => void): grpcWeb.ClientReadableStream<api_common_proto_storeservice_store_service_pb.GetStorePriceForProductResponse>;

  getStorePriceForProduct(
    request: api_common_proto_storeservice_store_service_pb.GetStorePriceForProductRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: api_common_proto_storeservice_store_service_pb.GetStorePriceForProductResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/api.common.proto.storeservice.StoreService/GetStorePriceForProduct',
        request,
        metadata || {},
        this.methodDescriptorGetStorePriceForProduct,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/api.common.proto.storeservice.StoreService/GetStorePriceForProduct',
    request,
    metadata || {},
    this.methodDescriptorGetStorePriceForProduct);
  }

}

