// source: api/common/proto/brandservice/brand_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.exportSymbol('proto.api.common.proto.brandservice.GetBrandRequest', null, global);
goog.exportSymbol('proto.api.common.proto.brandservice.GetBrandResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.brandservice.GetBrandRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.api.common.proto.brandservice.GetBrandRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.brandservice.GetBrandRequest.displayName = 'proto.api.common.proto.brandservice.GetBrandRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.api.common.proto.brandservice.GetBrandResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.api.common.proto.brandservice.GetBrandResponse.repeatedFields_, null);
};
goog.inherits(proto.api.common.proto.brandservice.GetBrandResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.api.common.proto.brandservice.GetBrandResponse.displayName = 'proto.api.common.proto.brandservice.GetBrandResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.brandservice.GetBrandRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.brandservice.GetBrandRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.brandservice.GetBrandRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.brandservice.GetBrandRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.RequestHeader.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.brandservice.GetBrandRequest}
 */
proto.api.common.proto.brandservice.GetBrandRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.brandservice.GetBrandRequest;
  return proto.api.common.proto.brandservice.GetBrandRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.brandservice.GetBrandRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.brandservice.GetBrandRequest}
 */
proto.api.common.proto.brandservice.GetBrandRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.RequestHeader;
      reader.readMessage(value,proto.api.common.proto.RequestHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.brandservice.GetBrandRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.brandservice.GetBrandRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.brandservice.GetBrandRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.brandservice.GetBrandRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.RequestHeader.serializeBinaryToWriter
    );
  }
};


/**
 * optional api.common.proto.RequestHeader header = 1;
 * @return {?proto.api.common.proto.RequestHeader}
 */
proto.api.common.proto.brandservice.GetBrandRequest.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.RequestHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.RequestHeader, 1));
};


/**
 * @param {?proto.api.common.proto.RequestHeader|undefined} value
 * @return {!proto.api.common.proto.brandservice.GetBrandRequest} returns this
*/
proto.api.common.proto.brandservice.GetBrandRequest.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.brandservice.GetBrandRequest} returns this
 */
proto.api.common.proto.brandservice.GetBrandRequest.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.brandservice.GetBrandRequest.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.api.common.proto.brandservice.GetBrandResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.api.common.proto.brandservice.GetBrandResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.api.common.proto.brandservice.GetBrandResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.brandservice.GetBrandResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
header: (f = msg.getHeader()) && proto.api.common.proto.ResponseHeader.toObject(includeInstance, f),
brandsList: jspb.Message.toObjectList(msg.getBrandsList(),
    proto.api.common.proto.Brand.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.api.common.proto.brandservice.GetBrandResponse}
 */
proto.api.common.proto.brandservice.GetBrandResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.api.common.proto.brandservice.GetBrandResponse;
  return proto.api.common.proto.brandservice.GetBrandResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.api.common.proto.brandservice.GetBrandResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.api.common.proto.brandservice.GetBrandResponse}
 */
proto.api.common.proto.brandservice.GetBrandResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.api.common.proto.ResponseHeader;
      reader.readMessage(value,proto.api.common.proto.ResponseHeader.deserializeBinaryFromReader);
      msg.setHeader(value);
      break;
    case 2:
      var value = new proto.api.common.proto.Brand;
      reader.readMessage(value,proto.api.common.proto.Brand.deserializeBinaryFromReader);
      msg.addBrands(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.api.common.proto.brandservice.GetBrandResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.api.common.proto.brandservice.GetBrandResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.api.common.proto.brandservice.GetBrandResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeader();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.api.common.proto.ResponseHeader.serializeBinaryToWriter
    );
  }
  f = message.getBrandsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.api.common.proto.Brand.serializeBinaryToWriter
    );
  }
};


/**
 * optional api.common.proto.ResponseHeader header = 1;
 * @return {?proto.api.common.proto.ResponseHeader}
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.getHeader = function() {
  return /** @type{?proto.api.common.proto.ResponseHeader} */ (
    jspb.Message.getWrapperField(this, proto.api.common.proto.ResponseHeader, 1));
};


/**
 * @param {?proto.api.common.proto.ResponseHeader|undefined} value
 * @return {!proto.api.common.proto.brandservice.GetBrandResponse} returns this
*/
proto.api.common.proto.brandservice.GetBrandResponse.prototype.setHeader = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.api.common.proto.brandservice.GetBrandResponse} returns this
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.clearHeader = function() {
  return this.setHeader(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.hasHeader = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated api.common.proto.Brand brands = 2;
 * @return {!Array<!proto.api.common.proto.Brand>}
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.getBrandsList = function() {
  return /** @type{!Array<!proto.api.common.proto.Brand>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.api.common.proto.Brand, 2));
};


/**
 * @param {!Array<!proto.api.common.proto.Brand>} value
 * @return {!proto.api.common.proto.brandservice.GetBrandResponse} returns this
*/
proto.api.common.proto.brandservice.GetBrandResponse.prototype.setBrandsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.api.common.proto.Brand=} opt_value
 * @param {number=} opt_index
 * @return {!proto.api.common.proto.Brand}
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.addBrands = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.api.common.proto.Brand, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.api.common.proto.brandservice.GetBrandResponse} returns this
 */
proto.api.common.proto.brandservice.GetBrandResponse.prototype.clearBrandsList = function() {
  return this.setBrandsList([]);
};


